CREATE TABLE drip_drop_reminders (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    plant_id INTEGER REFERENCES drip_drop_plants(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL,
    water_every INTEGER NOT NULL,
    remind_on --left off here, see what you have to do as far as appointment
);